### ISSUE TITLE
Add transparency to the overlay

### ISSUE THREAD

**Issue by AndrioJonatas** [jangxx/LeapOVRPassthrough#1]
**_Is it possible to add transparency option even via line of code?_**

**Comment by jangxx** [comment]
Yes it would be possible. Reading the openvr documentation, there is a method called `SetOverlayAlpha` which does exactly that (https://github.com/ValveSoftware/openvr/wiki/IVROverlay::SetOverlayAlpha).

You could add it to this project by adding the lines

```cpp
err = vr::VROverlay()->SetOverlayAlpha(m_ulOverlayHandle, 0.5); // change 0.5 to the desired transparency

if (err != vr::VROverlayError_None) {
    std::cout << "SetOverlayAlpha error: " << err << std::endl;
}
```

after line 62 in OVROverlayController.cpp, i.e. right [here](https://github.com/jangxx/LeapOVRPassthrough/blob/master/LeapOVRPassthrough/OVROverlayController.cpp#L62).

**Comment by AndrioJonatas** [comment]
> Yes it would be possible. Reading the openvr documentation, there is a method called `SetOverlayAlpha` which does exactly that (https://github.com/ValveSoftware/openvr/wiki/IVROverlay::SetOverlayAlpha).
> 
> You could add it to this project by adding the lines
> 
> ```c++
> err = vr::VROverlay()->SetOverlayAlpha(m_ulOverlayHandle, 0.5); // change 0.5 to the desired transparency
> 
> if (err != vr::VROverlayError_None) {
>     std::cout << "SetOverlayAlpha error: " << err << std::endl;
> }
> ```
> 
> after line 62 in OVROverlayController.cpp, i.e. right [here](https://github.com/jangxx/LeapOVRPassthrough/blob/master/LeapOVRPassthrough/OVROverlayController.cpp#L62).

Could you program in .exe with this option? **It took advantage and informed where the size of the SBS effect increases.**

**Comment by jangxx** [comment]
>Could you program in .exe with this option?

Sorry, but I have basically abandoned this project. Ever since I got a Valve Index in 2021, I haven't used this software and I'm not planning on developing it any further. I have just added an MIT license however, so feel free to pick up development and add all the features you need.

>It took advantage and informed where the size of the SBS effect increases.

I don't understand what you mean by that.
