### ISSUE TITLE
No longer working with latest versions of sdk

### ISSUE THREAD

**Issue by xNanochip** [jangxx/LeapOVRPassthrough#2]
It seems this app no longer works with the latest versions of Leapmotion sdk. Any chance this could be updated?
![image](https://github.com/jangxx/LeapOVRPassthrough/assets/10001888/adf46717-61c0-45dc-b55d-270cbc713715)

**Comment by jangxx** [comment]
I haven't actually used or updated this software since 2021, so I think it can be considered abandoned by now. If I ever find the time I might look into compiling it with the latest SDK version and fixing some of the bugs, but I have to be honest and say it's very unlikely.

**Comment by xNanochip** [comment]
So replacing the DLL with [this one](https://github.com/SDraw/driver_leap/blob/master/vendor/LeapSDK/lib/x64/LeapC.dll) works, however the camera view is rotated 90 degrees. Would you happen to know where in the code I might be able to fix that off hand? I appreciate any guidance you can offer.

![image](https://github.com/jangxx/LeapOVRPassthrough/assets/10001888/94c04775-7c9c-42bd-89a8-9c2cfe8c8d6a)

**Comment by jangxx** [comment]
Looks like you're in luck - I had some time today and just released a new version 1.2.0, which updates the SDK to the latest version and also adds an option into the tray menu to rotate the overlay. This should hopefully address all of your problems.
