### ISSUE TITLE
3D passthrough?

### ISSUE THREAD

**Issue by Charmandrigo** [jangxx/LeapOVRPassthrough#3]
I notice the app only passes the left camera as passthrough, but could there be a way of combining both cameras, one per eye, so you get a proper 3D passthrough? similar to how the passthrough of Windows Mixed Reality worked. there could be automatic offsets for the OG leap motion controller, the Stereo IR170 and the LM controller 2

**Comment by jangxx** [comment]
Sadly this is not possible, since SteamVR overlays can only display 2D textures and there's also no way to use a custom shader or have different overlays per eye.
